import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { useRouter } from 'expo-router';
import { GradientBackground } from '../components/GradientBackground';
import { Ionicons } from '@expo/vector-icons';
import useThemeStore from '../store/useThemeStore';

export default function PrivacyPolicyScreen() {
  const router = useRouter();
  const { currentTheme } = useThemeStore();

  return (
    <GradientBackground>
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
            <Ionicons name="chevron-back" size={28} color={currentTheme.colors.text.primary} />
          </TouchableOpacity>
          <Text style={[styles.title, { color: currentTheme.colors.text.primary }]}>Gizlilik Politikası</Text>
        </View>

        <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
          <View style={styles.contentCard}>
            <Text style={[styles.lastUpdated, { color: currentTheme.colors.text.muted }]}>Last updated: April 30, 2026</Text>
            
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </Text>

            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>
              We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </Text>

            <Text style={[styles.sectionTitle, { color: currentTheme.colors.primary }]}>Interpretation and Definitions</Text>
            <Text style={[styles.subSectionTitle, { color: currentTheme.colors.text.primary }]}>Interpretation</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>
              The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </Text>

            <Text style={[styles.subSectionTitle, { color: currentTheme.colors.text.primary }]}>Definitions</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>For the purposes of this Privacy Policy:</Text>
            
            <View style={styles.bulletList}>
              {[
                { label: 'Account', text: 'means a unique account created for You to access our Service or parts of our Service.' },
                { label: 'Affiliate', text: 'means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' },
                { label: 'Application', text: 'refers to Selfplace, the software program provided by the Company.' },
                { label: 'Company', text: '(referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Selfplace.' },
                { label: 'Country', text: 'refers to: Turkey' },
                { label: 'Device', text: 'means any device that can access the Service such as a computer, a cell phone or a digital tablet.' },
                { label: 'Personal Data', text: '(or "Personal Information") is any information that relates to an identified or identifiable individual.' },
                { label: 'Service', text: 'refers to the Application.' },
                { label: 'Service Provider', text: 'means any natural or legal person who processes the data on behalf of the Company.' },
                { label: 'Usage Data', text: 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.' },
                { label: 'You', text: 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.' },
              ].map((item, index) => (
                <Text key={index} style={[styles.bulletItem, { color: currentTheme.colors.text.primary }]}>
                  <Text style={{ fontWeight: 'bold' }}>{item.label}: </Text>{item.text}
                </Text>
              ))}
            </View>

            <Text style={[styles.sectionTitle, { color: currentTheme.colors.primary }]}>Collecting and Using Your Personal Data</Text>
            <Text style={[styles.subSectionTitle, { color: currentTheme.colors.text.primary }]}>Types of Data Collected</Text>
            
            <Text style={[styles.subSectionTitle, { color: currentTheme.colors.text.secondary, fontSize: 16 }]}>Personal Data</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary, marginLeft: 16 }]}>• Email address</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary, marginLeft: 16 }]}>• First name and last name</Text>

            <Text style={[styles.subSectionTitle, { color: currentTheme.colors.text.secondary, fontSize: 16 }]}>Usage Data</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>
              Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, and other diagnostic data.
            </Text>

            <Text style={[styles.sectionTitle, { color: currentTheme.colors.primary }]}>Use of Your Personal Data</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>The Company may use Personal Data for the following purposes:</Text>
            <View style={styles.bulletList}>
              {[
                'To provide and maintain our Service, including to monitor usage.',
                'To manage Your Account and registration as a user.',
                'For the performance of a contract or purchase agreement.',
                'To contact You via email, SMS, or push notifications regarding updates or informative communications.',
                'We do not send promotional or marketing emails. We may only contact You for account-related, security, support, password reset, or important service information.',
                'To manage Your requests and attend to Your inquiries.',
                'For business transfers, mergers, or acquisitions.',
              ].map((item, index) => (
                <Text key={index} style={[styles.bulletItem, { color: currentTheme.colors.text.primary }]}>• {item}</Text>
              ))}
            </View>

            <Text style={[styles.sectionTitle, { color: currentTheme.colors.primary }]}>Retention of Your Personal Data</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Account information is typically retained for the duration of your account relationship plus up to 24 months.
            </Text>

            <Text style={[styles.sectionTitle, { color: currentTheme.colors.primary }]}>Security of Your Personal Data</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </Text>

            <Text style={[styles.sectionTitle, { color: currentTheme.colors.primary }]}>Contact Us</Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.text.primary }]}>
              If you have any questions about this Privacy Policy, You can contact us:
            </Text>
            <Text style={[styles.paragraph, { color: currentTheme.colors.primary, fontWeight: 'bold' }]}>
              By email: selfplace.support@gmail.com
            </Text>
          </View>
        </ScrollView>
      </View>
    </GradientBackground>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 60,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  backButton: {
    marginRight: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  contentCard: {
    padding: 20,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  lastUpdated: {
    fontSize: 14,
    marginBottom: 24,
    fontStyle: 'italic',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 32,
    marginBottom: 16,
  },
  subSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginTop: 20,
    marginBottom: 12,
  },
  paragraph: {
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 16,
    opacity: 0.9,
  },
  bulletList: {
    marginVertical: 12,
  },
  bulletItem: {
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 12,
    paddingLeft: 8,
  }
});
